// PX2UIDefine.hpp

#ifndef PX2UIDEFINE_HPP
#define PX2UIDEFINE_HPP

#include "PX2UIPre.hpp"
#include "PX2APoint.hpp"
#include "PX2AVector.hpp"

namespace PX2
{

	class UIFrame;

	enum UICallType
	{
		UICT_NONE = 0,
		UICT_PRESSED,
		UICT_RELEASED,
		UICT_PRESSED_NOTPICK,
		UICT_RELEASED_NOTPICK,
		UICT_DOUBLECLICK,
		UICT_PROGRESSCHANGED,
		UICT_SLIDERCHANGED,
		UICT_EDITBOX_ATTACHWITHIME,
		UICT_EDITBOX_DETACHWITHIME,
		UICT_EDITBOX_TEXTCHANGED,
		UICT_EDITBOX_ENTER,
		UICT_CHECKED,
		UICT_DISCHECKED,
		UICT_LIST_SELECTED,
		UICT_TABFRAME_DRAG_BEGIN,
		UICT_TABFRAME_DRAG_END,
		UICT_COMBOBOX_CHOOSED,
		UICT_TABFRAME_SETACTIVE,
		UICT_SPLITTER_DRAGING,
		UICT_MAX_TYPE
	};

	enum UIPickType
	{
		UIPT_NONE = 0,
		UIPT_PRESSED,
		UIPT_RELEASED,
		UIPT_MOVED,
		UIPT_WHELLED,
		UIPT_MAX_TYPE
	};

	class PX2_ENGINE_ITEM UIInputData
	{
	public:
		UIInputData();
		~UIInputData();

		enum MouseTag
		{
			MT_NONE,
			MT_LEFT,
			MT_RIGHT,
			MT_MIDDLE,
			MT_MAX_TYPE
		};
		MouseTag TheMouseTag;

		UIPickType PickType;

		APoint WorldPos;
		AVector MoveDelta;
		float Wheel;
	};

	typedef void(*UICallback) (UIFrame *frame, UICallType type);

	enum UILayoutPosType
	{
		UILPT_LEFT,
		UILPT_RIGHT,
		UILPT_BOTTOM,
		UILPT_TOP,
		UILPT_CENTER,
		UILPT_ALL,
		UILPT_MAX_TYPE
	};

}

#endif